- name: Get Linux Kernel Version
  ansible.builtin.shell: uname -r
  register: kernel_version_output

- name: Set Kernel Version Fact
  set_fact:
    kernel_version: "{{ kernel_version_output.stdout }}"

- name: Gather System Facts
  ansible.builtin.setup:
  register: system_facts

- name: Generate HTML Report
  ansible.builtin.template:
    src: kernel_report_template.j2
    dest: /var/www/html/linux/kernel_report.html
  delegate_to: localhost
