
- name: Get Linux Kernel Version
  ansible.builtin.shell: uname -r
  register: kernel_version_output

- name: Set Kernel Version Fact
  set_fact:
    kernel_version: "{{ kernel_version_output.stdout }}"

- name: Gather System Facts
  ansible.builtin.setup:
  register: system_facts

- name: Read Existing Report
  ansible.builtin.slurp:
    path: /path/to/existing/kernel_report.html
  register: existing_report_content

- name: Include Existing Report
  set_fact:
    existing_report: "{{ existing_report_content.content | b64decode | default('') }}"

- name: Update HTML Report
  ansible.builtin.template:
    src: kernel_report_template.j2
    dest: /path/to/local/kernel_report_updated.html
