
- name: Get Kernel Version
  command: uname -r
  register: kernel_version_output

- name: Set Facts
  set_fact:
    kernel_version: "{{ kernel_version_output.stdout }}"
    ansible_dist: "{{ ansible_distribution }}"
    hostname: "{{ ansible_hostname }}"
    version: "{{ ansible_distribution_version }}"

- name: Debug Kernel Version
  debug:
    msg: "{{ inventory_hostname }} {{ansible_dist }}  {{ kernel_version }} {{ hostname }} {{ version }}"

- name: create HTML report
  template:
    src: report.j2
    dest: /tmp/kernel_report.html
#    owner: root
#    group: root
#    dest: /home/{{ ansible_ssh_user }}/kernel_report.html
  delegate_to: ansible-awx
#  delegate_to: localhost
  run_once: true
  become: no




#- name: Remove file (delete file)
#  ansible.builtin.file:
#    path: /home/fthadmin/kernel_report.html
#    state: absent
#  delegate_to: ansible-awx
#  run_once: true

- name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
  ansible.builtin.copy:
    src: /tmp/kernel_report.html
    dest: /var/www/html/linux/kernel_report.html
    owner: root
    group: root
    mode: '0644'
    backup: yes
  delegate_to: ansible-awx