
- name: Get Kernel Version
  command: uname -r
  register: kernel_version_output

- name: Set Facts
  set_fact:
    kernel_version: "{{ kernel_version_output.stdout }}"
    ansible_dist: "{{ ansible_distribution }}"
    hostname: "{{ ansible_hostname }}"
    version: "{{ ansible_distribution_version }}"

- name: Debug Kernel Version
  debug:
    msg: "{{ inventory_hostname }} {{ansible_dist }}  {{ kernel_version }} {{ hostname }} {{ version }}"

- name: create HTML report
  template:
    src: report.j2
    dest: /home/{{ ansible_ssh_user }}/kernel_report.html
  delegate_to: localhost
  run_once: true